CREATE TABLE IF NOT EXISTS patients
(
  id SERIAL PRIMARY KEY,
  patient_number INTEGER UNIQUE,
  patient_identifier VARCHAR(100),
  health_insurance VARCHAR(100),
  anonymous BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS triage_sessions
(
  id SERIAL PRIMARY KEY,
  session_id UUID NOT NULL UNIQUE,
  patient_id INTEGER REFERENCES patients(id) ON DELETE SET NULL,
  current_question VARCHAR(100),
  priority_level VARCHAR(50),
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS queue
(
  id SERIAL PRIMARY KEY,
  session_id UUID NOT NULL UNIQUE,
  patient_id INTEGER REFERENCES patients(id) ON DELETE SET NULL,
  priority_level VARCHAR(50) NOT NULL,
  queue_position INTEGER,
  status VARCHAR(50) NOT NULL DEFAULT 'waiting',
  about_details TEXT,
  queued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs
(
  id SERIAL PRIMARY KEY,
  session_id UUID,
  actor_name VARCHAR(150) NOT NULL,
  actor_role VARCHAR(50) NOT NULL,
  action VARCHAR(150) NOT NULL,
  details JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
